<a href="https://colab.research.google.com/github/La-Talia/Pytorch-practice/blob/main/pythorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

# **Tensor**

In [8]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)

tensor([[ 1.1665,  0.3466, -0.9938,  0.2678],
        [-1.5665,  1.0935,  1.2341,  0.9340],
        [ 1.0226, -0.2909, -1.3471, -0.6557]])


In [9]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [11]:
my_torch = torch.arange(10)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Reshape and view

In [12]:
my_torch = my_torch.reshape(2,5)
print(my_torch)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [15]:
my_torch = my_torch.reshape(-1,5)
print(my_torch)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [16]:
my_torch2 = my_torch.view(5,-1)
print(my_torch2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [18]:
my_torch[1] = 987
print(my_torch)
print(my_torch2)

tensor([[  0,   1,   2,   3,   4],
        [987, 987, 987, 987, 987]])
tensor([[  0,   1],
        [  2,   3],
        [  4, 987],
        [987, 987],
        [987, 987]])


In [20]:
print(my_torch[0])

tensor([0, 1, 2, 3, 4])


Tensor Math operations

In [21]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [23]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [24]:
#addition long hand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
#subtration
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [27]:
#sub function
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [28]:
#multiply
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [29]:
#mul func
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [31]:
#div
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [30]:
#division
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [32]:
#remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])